language: php
php:
  - '7.0'
  - '7.1'

install:
  - composer install

script:
  - mkdir -p build/logs
  - bin/phpunit tests --coverage-clover build/logs/coverage.xml

after_script:
- bin/coveralls -v --coverage_clover build/logs/coverage.xml